//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EUC.Locales {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EUC.Locales.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download GDPR agreement.
        /// </summary>
        public static string Button_DownloadGdpr {
            get {
                return ResourceManager.GetString("Button_DownloadGdpr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Button_Send {
            get {
                return ResourceManager.GetString("Button_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czech.
        /// </summary>
        public static string DropdownItem_Language_Czech {
            get {
                return ResourceManager.GetString("DropdownItem_Language_Czech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string DropdownItem_Language_English {
            get {
                return ResourceManager.GetString("DropdownItem_Language_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czech.
        /// </summary>
        public static string DropdownItem_Nationality_Czech {
            get {
                return ResourceManager.GetString("DropdownItem_Nationality_Czech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string DropdownItem_Nationality_Other {
            get {
                return ResourceManager.GetString("DropdownItem_Nationality_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slovak.
        /// </summary>
        public static string DropdownItem_Nationality_Slovak {
            get {
                return ResourceManager.GetString("DropdownItem_Nationality_Slovak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Man.
        /// </summary>
        public static string DropdownItem_Sex_Man {
            get {
                return ResourceManager.GetString("DropdownItem_Sex_Man", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string DropdownItem_Sex_Other {
            get {
                return ResourceManager.GetString("DropdownItem_Sex_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Woman.
        /// </summary>
        public static string DropdownItem_Sex_Woman {
            get {
                return ResourceManager.GetString("DropdownItem_Sex_Woman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday.
        /// </summary>
        public static string Label_Birthday {
            get {
                return ResourceManager.GetString("Label_Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter birthday.
        /// </summary>
        public static string Label_Birthday_RequiredError {
            get {
                return ResourceManager.GetString("Label_Birthday_RequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth number.
        /// </summary>
        public static string Label_BirthNumber {
            get {
                return ResourceManager.GetString("Label_BirthNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter birthday.
        /// </summary>
        public static string Label_BirthNumber_RequiredError {
            get {
                return ResourceManager.GetString("Label_BirthNumber_RequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Label_Email {
            get {
                return ResourceManager.GetString("Label_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter email.
        /// </summary>
        public static string Label_Email_RequiredError {
            get {
                return ResourceManager.GetString("Label_Email_RequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string Label_FirstName {
            get {
                return ResourceManager.GetString("Label_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter first name.
        /// </summary>
        public static string Label_FirstName_RequiredError {
            get {
                return ResourceManager.GetString("Label_FirstName_RequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I agree with GDPR.
        /// </summary>
        public static string Label_GdprAcceptance {
            get {
                return ResourceManager.GetString("Label_GdprAcceptance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To continue, you must agree with GDPR.
        /// </summary>
        public static string Label_GdprAcceptance_RequiredError {
            get {
                return ResourceManager.GetString("Label_GdprAcceptance_RequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have birth number.
        /// </summary>
        public static string Label_HasBirthNumber {
            get {
                return ResourceManager.GetString("Label_HasBirthNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select language.
        /// </summary>
        public static string Label_LanguageSelect {
            get {
                return ResourceManager.GetString("Label_LanguageSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string Label_LastName {
            get {
                return ResourceManager.GetString("Label_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter last name.
        /// </summary>
        public static string Label_LastName_RequiredError {
            get {
                return ResourceManager.GetString("Label_LastName_RequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationality.
        /// </summary>
        public static string Label_Nationality {
            get {
                return ResourceManager.GetString("Label_Nationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select nationality.
        /// </summary>
        public static string Label_Nationality_RequiredError {
            get {
                return ResourceManager.GetString("Label_Nationality_RequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sex.
        /// </summary>
        public static string Label_Sex {
            get {
                return ResourceManager.GetString("Label_Sex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select sex.
        /// </summary>
        public static string Label_Sex_RequiredError {
            get {
                return ResourceManager.GetString("Label_Sex_RequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading ....
        /// </summary>
        public static string Text_Loading {
            get {
                return ResourceManager.GetString("Text_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questionnaire.
        /// </summary>
        public static string Text_Questionnaire {
            get {
                return ResourceManager.GetString("Text_Questionnaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download the inserted data in JSON format.
        /// </summary>
        public static string Text_Questionnaire_DownloadInsertedDataJson {
            get {
                return ResourceManager.GetString("Text_Questionnaire_DownloadInsertedDataJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while processing the questionnaire..
        /// </summary>
        public static string Text_Questionnaire_Failed {
            get {
                return ResourceManager.GetString("Text_Questionnaire_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill out another questionnaire.
        /// </summary>
        public static string Text_Questionnaire_NextQuestionnaire {
            get {
                return ResourceManager.GetString("Text_Questionnaire_NextQuestionnaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for sending the questionnaire..
        /// </summary>
        public static string Text_Questionnaire_Success {
            get {
                return ResourceManager.GetString("Text_Questionnaire_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try again.
        /// </summary>
        public static string Text_Questionnaire_TryItAgain {
            get {
                return ResourceManager.GetString("Text_Questionnaire_TryItAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date part of birth number is not correct.
        /// </summary>
        public static string Validation_BirthNumber_DateConversionFailed {
            get {
                return ResourceManager.GetString("Validation_BirthNumber_DateConversionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The birth number must have 9 or 10 digits (possibly with a slash after the sixth digit).
        /// </summary>
        public static string Validation_BirthNumber_DigitsCount {
            get {
                return ResourceManager.GetString("Validation_BirthNumber_DigitsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The birth number can only contain digits and an optional slash.
        /// </summary>
        public static string Validation_BirthNumber_OnlyDigitsOneSlash {
            get {
                return ResourceManager.GetString("Validation_BirthNumber_OnlyDigitsOneSlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If a slash is used, it must be in the seventh position.
        /// </summary>
        public static string Validation_BirthNumber_SlashPosition {
            get {
                return ResourceManager.GetString("Validation_BirthNumber_SlashPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email address format around character &quot;@&quot;.
        /// </summary>
        public static string Validation_Email_EmptyParts {
            get {
                return ResourceManager.GetString("Validation_Email_EmptyParts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect email address format in the part after the &quot;@&quot; sign.
        /// </summary>
        public static string Validation_Email_InvalidDomain {
            get {
                return ResourceManager.GetString("Validation_Email_InvalidDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email address format.
        /// </summary>
        public static string Validation_Email_InvalidFormat {
            get {
                return ResourceManager.GetString("Validation_Email_InvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email address format in the part before the &quot;@&quot; character.
        /// </summary>
        public static string Validation_Email_InvalidLocalPart {
            get {
                return ResourceManager.GetString("Validation_Email_InvalidLocalPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing &quot;@&quot; character.
        /// </summary>
        public static string Validation_Email_MissingAt {
            get {
                return ResourceManager.GetString("Validation_Email_MissingAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address cannot contain any spaces.
        /// </summary>
        public static string Validation_Email_NoSpaces {
            get {
                return ResourceManager.GetString("Validation_Email_NoSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name contains invalid characters.
        /// </summary>
        public static string Validation_Name_HasInvalidCharacters {
            get {
                return ResourceManager.GetString("Validation_Name_HasInvalidCharacters", resourceCulture);
            }
        }
    }
}
